src/Entity/Game.php
<?php

namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    private $btnAdd;
    private $btnChange;
    private $btnDelete;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $release_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $review;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $publisher;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Plattform", inversedBy="title")
     */
    private $plattform;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Entwickler", inversedBy="games")
     */
    private $entwicklers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Genre", inversedBy="games")
     */
    private $Genre;


    public function __construct()
    {
        $this->plattform = new ArrayCollection();
        $this->entwicklers = new ArrayCollection();
        $this->Genre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getReleaseDate(): ?int
    {
        return $this->release_date;
    }

    public function setReleaseDate(?int $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->review;
    }

    public function setReview(?string $review): self
    {
        $this->review = $review;

        return $this;
    }


    public function getPublisher(): ?string
    {
        return $this->publisher;
    }

    public function setPublisher(?string $publisher): self
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getBtnAdd(){
        $this->btnAdd;
    }

    public function setBtnAdd($btnAdd){
        $this->btnAdd=$btnAdd;
    }

    public function getBtnChange(){
        $this->btnChange;
    }

    public function setBtnChange($btnChange){
        $this->btnChange=$btnChange;
    }

    public function getBtnDelete(){
        $this->btnDelete;
    }

    public function setBtnDelete($btnDelete){
        $this->btnDelete=$btnDelete;
    }

    /**
     * @return Collection|Plattform[]
     */
    public function getPlattform(): Collection
    {
        return $this->plattform;
    }

    public function addPlattform(Plattform $plattform): self
    {
        if (!$this->plattform->contains($plattform)) {
            $this->plattform[] = $plattform;
        }

        return $this;
    }

    public function removePlattform(Plattform $plattform): self
    {
        if ($this->plattform->contains($plattform)) {
            $this->plattform->removeElement($plattform);
        }

        return $this;
    }

    /**
     * @return Collection|Entwickler[]
     */
    public function getEntwicklers(): Collection
    {
        return $this->entwicklers;
    }

    public function addEntwickler(Entwickler $entwickler): self
    {
        if (!$this->entwicklers->contains($entwickler)) {
            $this->entwicklers[] = $entwickler;
            $entwickler->addGame($this);
        }

        return $this;
    }

    public function removeEntwickler(Entwickler $entwickler): self
    {
        if ($this->entwicklers->contains($entwickler)) {
            $this->entwicklers->removeElement($entwickler);
            $entwickler->removeGame($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */

    public function addGenre(Genre $genre): self
    {
        if (!$this->Genre->contains($genre)) {
            $this->Genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->Genre->contains($genre)) {
            $this->Genre->removeElement($genre);
        }

        return $this;
    }
}

src/Form/Type/GameType.php
<?php
/**
 * Created by PhpStorm.
 * User: justinglowa
 * Date: 12.12.18
 * Time: 15:43
 */

namespace App\Form\Type;

use App\Entity\Entwickler;
use App\Entity\Game;
use App\Entity\Plattform;
use App\Entity\Genre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options){
        //dump($this->getYears());
//       exit();
        $builder
            ->add('title', TextType::class)
            ->add('Genre', EntityType::class, array(
                'class' => Genre::class,
                'expanded' => true,
                'multiple' => true
            ))
//            ->add('genre', ChoiceType::class, array(
//                'choices' => array(
//                    'Action' => 'Action',
//                    'Adventure' => 'Adventure',
//                    'ActionAdventrue' => 'ActionAdventure',
//                    'Rollenspiel(RPG)' => 'Rollenspiel(RPG)',
//                    'Strategie' => 'Strategie',
//                    'First Person Shooter(FPS)' => 'First Person Shooter(FPS)',
//                    'Sport' => 'Sport',
//                    'Open World' => 'Open-World'
//                )
//            ))
            ->add('release_date', choiceType::class, array(
                'choices' => $this->getYears()

            ))
            ->add('review',ChoiceType::class, array(
                'choices' => $this->getReview()

            ))
            ->add('publisher', ChoiceType::class, array(
                'choices' => array(
                    'Electronic Arts(EA)' => 'Electronic Arts',
                    'Nintendo' => 'Nintendo',
                    '2K' => '2K',
                    'Activision Blizzard' => 'Activision Blizzard',
                    'Ubisoft' => 'Ubisoft'
                )
            ))


            ->add('entwicklers', EntityType::class, array(
                'class' => Entwickler::class,
                'expanded' => true,
                'multiple' => true,

            ))
            ->add('plattform', EntityType::class, array(
                'class' => Plattform::class,
                'expanded' => true,
                'multiple' => true,


            ))
        ;
        if ($options['edit']){
            $builder
                ->add('btnChange', SubmitType::class,array('label' => 'bearbeiten'));
        }else {
            $builder
            ->add('btnAdd', SubmitType::class, array('label' => 'Hinzufügen'));
        }
    }

    public function configureOptions(OptionsResolver $resolver){
        $resolver->setDefaults(array(
           'data_class' =>  Game::class,
            'edit' => null,
        ));
    }

    public function getYears(){
        $year = array();
        $now = date('Y');
        for($yearCount = 1965; $yearCount <= $now; $yearCount++) {
            $year[$yearCount] = $yearCount;
        }
        return $year;
    }

    public function getReview(){
        $review = array();
        for($i=0;$i <= 100; $i++){
            if($i%5==0){
            $review[$i.'/100']= $i.'/100';
            }
        }
        return $review;
    }


}

templates/games/addGame.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

<h1>Games hinzufügen</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <a href= "{{ path("app_game_index") }}"><button type="button" class="btn btn-danger" name="btnCancel">Abbruch</button></a>

{% endblock %}

templates/games/addSuccess.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

    <h1>Datensatz erfolgreich gespeichert!</h1>
    <div>
        <p>möchten Sie einen weiteren Datensatz einfüen?</p>
        <a href= "{{ path("app_game_addGame") }}"><button type="button" name="btnYes">yes</button></a>
        <a href= "{{ path("app_game_index") }}"><button type="button" name="btnNo">no</button></a>
    </div>
{% endblock %}

templates/games/changeGame.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

    <h1>Eintrag bearbeiten</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
        <a href= "{{ path("app_game_index") }}"><button type="button" class="btn btn-danger" name="btnCancel">Abbruch</button></a>

{% endblock %}

templates/games/deleteGame.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

    <h1>sind Sie sicher dass Sie diesen Datensatz löschen wollen?</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <a href= "{{ path("app_game_index") }}"><button type="button" class="btn btn-danger" name="btnCancel">nein</button></a>

{% endblock %}

templates/games/deleteSuccess.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

    <h1>Datensatz erfolgreich gespeichert!</h1>
    <div>
        <p>Datensatz erfolgriech gelöscht</p>
        <a href= "{{ path("app_game_index") }}"><button type="button" name="btnNo">zurück zu Index</button></a>
    </div>
{% endblock %}

templates/games/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Games Liste{% endblock %}

{% block body %}

    <h1>Welcome</h1>

    <div>

<div class="row">
        <table class="table-responsive-md justify-content-sm-center">
            <thead >
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Genre</th>
                    <th scope="col">Release Year</th>
                    <th scope="col">Plattform</th>
                    <th scope="col">Review Score</th>
                    <th scope="col">Entwickler</th>
                    <th scope="col">Publisher</th>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
            {% for game in games %}

            <tr>
                <td scope="row">{{ game.id }}</td>
                <td>{{ game.title }}</td>
                <td>{{ game.genre|join('<br>')|raw }}</td>
                <td>{{ game.releaseDate }}</td>
                <td>{{ game.plattform|join('<br>')|raw }}</td>
                <td>{{ game.review }}</td>
                <td>{{ game.entwicklers|join('<br>')|raw }}</td>
                <td>{{ game.publisher }}</td>
                <td><a href= "{{ path("app_game_changeGame", {'id':game.id}) }}"><button type="button" class="btn btn-primary btn-sm" id="btnChange" name="btnChange">Eintrag ändern</button></a></td>
                <td><a href= "{{ path("app_game_deleteGame", {'id':game.id}) }}"><button type="button" class="btn btn-primary btn-sm" name="btnDelete">Eintrag löschen</button></a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>

        <a href= "{{ path("app_game_addGame") }}"><button type="button" class="btn btn-primary" name="btnYes">Spiel Hinzufügen</button></a>
    </div>

{% endblock %}

{#bootstrap tests#}

{#<div class="row" class="border">#}
            {#<div class="col-sm">ID</div>#}
            {#<div class="col-sm">Title</div>#}
            {#<div class="col-sm">Genre</div>#}
            {#<div class="col-sm">Release Date(Yr)</div>#}
            {#<div class="col-sm">Plattform</div>#}
            {#<div class="col-sm">Review Score</div>#}
            {#<div class="col-sm">Entwickler</div>#}
            {#<div class="col-sm">Publisher</div>#}
            {#<div class="col-sm"></div>#}
            {#<div class="col-sm"></div>#}
        {#</div>#}
        {#{% for game in games %}#}
        {#<div class="row">#}
            {#<div class="col-sm">{{ game.id }}</div>#}
            {#<div class="col-sm">{{ game.title }}</div>#}
            {#<div class="col-sm">{{ game.genre }}</div>#}
            {#<div class="col-sm">{{ game.releaseDate }}</div>#}
            {#<div class="col-sm">{{ game.plattform|join('<br>')|raw }}</div>#}
            {#<div class="col-sm">{{ game.review }}</div>#}
            {#<div class="col-sm">{{ game.entwicklers|join('<br>') }}</div>#}
            {#<div class="col-sm">{{ game.publisher }}</div>#}
            {#<div class="col-sm"><a href= "{{ path("app_game_changeGame", {'id':game.id}) }}"><button type="button"  name="btnChange">Eintrag ändern</button></a></td></div>#}
            {#<div class="col-sm"><a href= "{{ path("app_game_deleteGame", {'id':game.id}) }}"><button type="button" name="btnDelete">Eintrag löschen</button></a></div>#}
        {#</div>#}
        {#{% endfor %}#}